#ifndef __SYSCALL_H
#define __SYSCALL_H

#define SYSCALL_EXIT	1
#define SYSCALL_FORK	2
#define SYSCALL_YIELD	3
#define SYSCALL_GETPID	4
#define SYSCALL_MOUNT	5
#define SYSCALL_OPEN	6
#define SYSCALL_CLOSE	7
#define SYSCALL_STAT	8
#define SYSCALL_READ	9
#define SYSCALL_WRITE	10
#define NSYSCALLS	11

#endif
